### ISSUE TITLE
Exception on presenter start

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#110]
I'm getting an exception on service start of the presenter if `PRESENTED_URL_DOMAIN` is not set:

```
> presenter@1.0.0 start /usr/src/app
> node app.js
/usr/src/app/src/helpers/request.js:12
return config.presented_url_domain() || this._request.get('Host');
^
TypeError: Cannot read property 'get' of null
 at Object.host (/usr/src/app/src/helpers/request.js:12:62)
 at Object.PathService.getTemplatesPath (/usr/src/app/src/services/path.js:15:56)
 at Object.<anonymous> (/usr/src/app/src/services/nunjucks.js:9:23)
 at Module._compile (module.js:460:26)
 at Object.Module._extensions..js (module.js:478:10)
 at Module.load (module.js:355:32)
 at Function.Module._load (module.js:310:12)
 at Module.require (module.js:365:17)
 at require (module.js:384:17)
 at Object.<anonymous> (/usr/src/app/src/services/template.js:6:15)
```

Not a blocker because I can just make sure that variable is set, but it would prevent us from supporting multi-domain instances.

**Comment by smashwilson** [comment]
Looks like this was fixed in refactoring a long time ago. Hooray!
