### ISSUE TITLE
moment.js deprecation warning

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#116]
This isn't fatal, but it's another stacktrace I'm seeing in the presenter logs.

```
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major re
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: Error
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at deprecate (/usr/src/app/node_modules/moment/moment.js:738:42)
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at /usr/src/app/node_modules/moment/moment.js:826:50
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at /usr/src/app/node_modules/moment/moment.js:8:85
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at Object.<anonymous> (/usr/src/app/node_modules/moment/moment.js:11:2)
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at Module._compile (module.js:460:26)
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at Object.Module._extensions..js (module.js:478:10)
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at Module.load (module.js:355:32)
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at Function.Module._load (module.js:310:12)
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at Module.require (module.js:365:17)
Jul 04 12:52:09 deconst-worker-drc-blue-001 systemd-docker[1056]: at require (module.js:384:17)
```

**Comment by ktbartholomew** [comment]
Yeah, it seems that dates come out of Jekyll as strings. We can do our own `new Date(jekyllDateString)` to avoid the deprecation warning, but that's basically the same thing moment.js is doing on its own.
