### ISSUE TITLE
Socket hang-up error

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#117]
This one happens when a connection gets terminated. Looks like we're assuming that an error is an HTTP error when it could be a different kind.

```
2015-07-03T21:44:07.773Z - error:  Error: socket hang up
 at createHangUpError (_http_client.js:215:15)
 at Socket.socketOnEnd (_http_client.js:293:23)
 at Socket.emit (events.js:129:20)
 at _stream_readable.js:908:16
 at process._tickCallback (node.js:355:11)
 /usr/src/app/src/routers/content.js:24
 if(error.statusCode.toString() === '404') {
 ^
 TypeError: Cannot read property 'toString' of undefined
 at handleError (/usr/src/app/src/routers/content.js:24:24)
 at /usr/src/app/src/routers/content.js:60:20
 at /usr/src/app/node_modules/async/lib/async.js:589:17
 at done (/usr/src/app/node_modules/async/lib/async.js:126:15)
 at /usr/src/app/node_modules/async/lib/async.js:32:16
 at /usr/src/app/node_modules/async/lib/async.js:586:21
 at Request._callback (/usr/src/app/src/services/content/index.js:32:24)
 at self.callback (/usr/src/app/node_modules/request/request.js:344:22)
 at Request.emit (events.js:107:17)
 at Request.onRequestError (/usr/src/app/node_modules/request/request.js:961:8)
```

**Comment by smashwilson** [comment]
@ktbartholomew By the way, you don't have to activate on these right away, I'm mostly filing them for my own reference as I see them in the logs :stuck_out_tongue:
