### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#119]
This just brought down a presenter:

```
 _http_outgoing.js:335
 throw new Error('Can\'t set headers after they are sent.');
 ^
 Error: Can't set headers after they are sent.
 at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
 at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:700:10)
 at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:154:12)
 at /usr/src/app/src/routers/content.js:106:17
 at /usr/src/app/src/services/content/filter.js:12:13
 at next (/usr/src/app/node_modules/mware/index.js:56:28)
 at /usr/src/app/src/routers/content.js:98:20
 at exec (/usr/src/app/node_modules/mware/index.js:50:23)
 at next (/usr/src/app/node_modules/mware/index.js:60:9)
 at /usr/src/app/src/routers/content.js:84:20
```

**Comment by smashwilson** [comment]
Oh right, this is the same trace from #114.
