### ISSUE TITLE
Improve bad credential error message

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#60]
While the content service is bootstrapping itself, `client.createContainer` appears to invoke its callback with a `null` instead of the created container:

```
/usr/src/app/src/connection.js:25
      log.debug("Enabling CDN on container [" + container.name + "].");
                                                         ^
TypeError: Cannot read property 'name' of undefined
    at cdnEnable (/usr/src/app/src/connection.js:25:58)
    at /usr/src/app/node_modules/pkgcloud/lib/pkgcloud/openstack/storage/client/containers.js:113:9
    at Object.exports.handle (/usr/src/app/node_modules/pkgcloud/node_modules/errs/lib/errs.js:206:5)
    at /usr/src/app/node_modules/pkgcloud/lib/pkgcloud/openstack/client.js:190:21
    at /usr/src/app/node_modules/pkgcloud/lib/pkgcloud/openstack/client.js:139:14
    at Request._callback (/usr/src/app/node_modules/pkgcloud/lib/pkgcloud/openstack/context/identity.js:124:14)
    at self.callback (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:123:22)
    at Request.emit (events.js:107:17)
    at ClientRequest.self.clientErrorHandler (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:244:10)
    at ClientRequest.emit (events.js:107:17)
```

**Comment by smashwilson** [comment]
I can replicate this if I provide an invalid (but not blank) `RACKSPACE_APIKEY`. We could stand to have a better error message, here.
