### ISSUE TITLE
Panic in etcd-watcher

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#64]
My etcd-watcher containers always die (not immediately, but somewhat quickly after launch) with this panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x456ee3]

goroutine 1 [running]:
github.com/coreos/etcd/etcdctl/command.environResponse(0x0, 0xc20800c5a0, 0x1d, 0x1d, 0x0, 0x0, 0x0)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:111 +0x643
github.com/coreos/etcd/etcdctl/command.execWatchCommandFunc(0xc208070580, 0xc20807a080, 0x5, 0x0, 0x0)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:87 +0x6cb
github.com/coreos/etcd/etcdctl/command.rawhandle(0xc208070580, 0x98a628, 0x4, 0x0, 0x0)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:72 +0x58a
github.com/coreos/etcd/etcdctl/command.handlePrint(0xc208070580, 0x98a628, 0x98a6d8)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:78 +0x32
github.com/coreos/etcd/etcdctl/command.handleKey(0xc208070580, 0x98a628)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:111 +0x3e
github.com/coreos/etcd/etcdctl/command.func·001(0xc208070580)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:39 +0x34
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x8d33b0, 0xa, 0x0, 0x0, 0x945c30, 0x2e, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:101 +0xe42
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc2080e6000, 0xc20800a000, 0x5, 0x5, 0x0, 0x0)
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:125 +0xb70
main.main()
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/main.go:58 +0xc45

goroutine 5 [syscall, 5 minutes]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 15 [chan receive, 2 minutes]:
github.com/coreos/etcd/etcdctl/command.func·002()
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:76 +0x48
created by github.com/coreos/etcd/etcdctl/command.execWatchCommandFunc
    /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:79 +0x536

goroutine 14 [runnable]:
net/http.(*persistConn).writeLoop(0xc208070160)
    /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:661 +0xcbc
```

I expect I'm misconfiguring something somewhere?

**Comment by smashwilson** [comment]
Here's a related issue: coreos/etcd#2693

**Comment by smashwilson** [comment]
The container has been stable on our dev cluster for about three days now, so I think we can say this is fixed :+1:

It must have been caused by the cluster misconfigurations.
